apps/login/urls.py
''' App URLS.py file. '''
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/travels/urls.py
"""travelbuddy travels app URL Configuration
"""
from django.conf.urls import url
from . import views

#app_name = travels -- set at project urls.py
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addplan$', views.addplan, name='addplan'),
    url(r'^viewplan/(?P<trip_id>\d+)$', views.viewplan, name='viewplan'),
]

travelbuddy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace="auth")),
    url(r'^travels/', include('apps.travels.urls', namespace="travels")),
]

apps/travels/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from ..login.models import User

# Create your models here.
class DestinationManager(models.Manager):
    def newtravelplanvalidate(self, postdata):
        results = {'status':True, 'errors':[]}
        if not postdata['destination'] or len(postdata['destination']) < 0:
            results['errors'].append("Destination is missing.")
            results['status'] = False
        if not postdata['description'] or len(postdata['description']) < 0:
            results['errors'].append("Description is missing.")
            results['status'] = False
        if not postdata['traveldatefrom']:
            results['errors'].append("Travel Departure Date is missing.")
            results['status'] = False
        else:
            if datetime.strptime(postdata['traveldatefrom'], "%Y-%m-%d") < datetime.today():
                results['errors'].append("Travel Departure Date must be in the future.")
                results['status'] = False
        if not postdata['traveldateto']:
            results['errors'].append("Travel Return Date is missing.")
            results['status'] = False
        else:
            if datetime.strptime(postdata['traveldateto'], "%Y-%m-%d") \
            < datetime.strptime(postdata['traveldatefrom'], "%Y-%m-%d"):
                results['errors'].append("Travel Return Date must be after departure date.")
                results['status'] = False
        if results['status'] is False:
            return results
        else:
            createtrip = Destination.objects.create(
                name=postdata['destination'],
                description=postdata['description'],
                traveldatefrom=postdata['traveldatefrom'],
                traveldateto=postdata['traveldateto'],
                planned_by_id=postdata['planned_by'])
            createtrip.participants.add(postdata['planned_by'])
            return results


class Destination(models.Model):
    ''' This is the main desctination module, aka Trips, and contains the Plan, aka description
    '''
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    traveldatefrom = models.DateField()
    traveldateto = models.DateField()
    planned_by = models.ForeignKey('login.User', related_name="UsersDestinations")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    participants = models.ManyToManyField(User, related_name="travel")
    objects = DestinationManager()

apps/travels/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from ..login import views
from models import Destination

# Create your views here.
def checklogin(request):
    try:
        request.session['id']
    except KeyError:
        request.session.flush()
        messages.error(request, 'Oh Snap! There is no session cookie detected, please login.')
        return False
    return True

def index(request):
    ''' Main landing page for the Travels app
    '''
    if checklogin(request):
        mytrips = Destination.objects.all().filter(planned_by=request.session['id'])
        otherstrips = Destination.objects.all().exclude(planned_by=request.session['id'])
        context = {
            'mytrips': mytrips,
            'otherstrips': otherstrips
        }
        return render(request, 'travels/index.html', context)
    else:
        return redirect('/')

def addplan(request):
    ''' This is the landing page to add travel plans
    '''
    if checklogin(request):
        if request.method == "POST":
            plandata = {
                'destination': request.POST['destination'],
                'description': request.POST['description'],
                'traveldatefrom': request.POST['traveldatefrom'],
                'traveldateto': request.POST['traveldateto'],
                'planned_by': request.session['id']
            }
            newtravelplanvalidate = Destination.objects.newtravelplanvalidate(plandata)
            if newtravelplanvalidate['status'] is False:
                for error in newtravelplanvalidate['errors']:
                    messages.error(request, error)
                return redirect('/travels/addplan')
            return redirect('/travels')
        else:
            return render(request, 'travels/addplan.html')
    else:
        return redirect('/')

def viewplan(request, trip_id):
    print 'viewplan works'
    trip = Destination.objects.get(id=trip_id)
    context = {
        'trips': trip,
        'participants': trip.participants.all()
    }
    return render(request,'travels/viewplan.html', context)

apps/travels/templates/travels/addplan.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <title>Add Travel Plans</title>
    <meta description='Add Travel Plans for TravelBuddy App'>
    <meta charset='utf-8'/>
</head>
<body>
    <div id='wrapper'>
        <h2> Add you travel plan {{ request.session.name }}... </h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{% url 'travels:addplan' %}" method="POST">
            {% csrf_token %}
            <label for="destination">Destination: </label>
            <input type="text" name="destination">
            <label for="description">Description: </label>
            <input type="text" name="description">
            <label for="traveldatefrom">Travel departure date: </label>
            <input type="date" name="traveldatefrom">
            <label for="traveldateto">Travel return date: </label>
            <input type="date" name="traveldateto">
            <br><br>
            <input type="submit" name="submit" value="Add Travel Plan">
        </form><br>
        <form action="{% url 'auth:logout' %}" method="GET">
            <button>Logout</button>
        </form>
    </div>
</body>
</html>

apps/travels/templates/travels/index.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <title>Main Page</title>
    <meta description='Main Page for LoginReg App'>
    <meta charset='utf-8'/>
</head>
<body>
    <div id='wrapper'>
        <h2> Welcome to the Travels App, {{ request.session.name }}... </h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div id=yourtripschedules>
            <h3>Your trip schedules</h3>
            {% if mytrips %}
            <table id="yourtriptable">
                <tr> 
                    <th>Destination</th>
                    <th>Travel Start Date</th>
                    <th>Travel End Date</th>
                    <th>Plan</th>
                </tr>
                {% for trip in mytrips %}
                <tr>                    
                    <td><a href="{% url 'travels:viewplan' trip.id %}">{{ trip.name }}</a></td>
                    <td>{{ trip.traveldatefrom }}</td>
                    <td>{{ trip.traveldateto }}</td>
                    <td>{{ trip.description }}</td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <p>No Data</p>
            {% endif %}
        </div>
        <div id="otherstripschedules">
            <h3>Others trip schedules</h3>
            {% if otherstrips %}
                <table id="yourtriptable">
                    <tr> 
                        <th>Destination</th>
                        <th>Travel Start Date</th>
                        <th>Travel End Date</th>
                        <th>Plan</th>
                        {% comment %}<th>Do you want to join?</th>{% endcomment %}
                    </tr>
                    {% for each in otherstrips %}
                    <tr>                    
                        <td><a href="{% url 'travels:viewplan' each.id %}">{{ each.name }}</a></td>
                        <td>{{ each.traveldatefrom }}</td>
                        <td>{{ each.traveldateto }}</td>
                        <td>{{ each.description }}</td>
                        {% comment %}<td>{% url 'travels:join' %}{% endcomment %}
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                    <p>No Data</p>
                </table>
            {% endif %}
        </div>
        <form action="{% url 'travels:addplan' %}" method="GET">
            <button>Add Travel Plan</button>
        </form><br>
        <form action="{% url 'auth:logout' %}" method="GET">
            <button>Logout</button>
        </form>
    </div>
</body>
</html>

apps/travels/templates/travels/viewplan.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <title>Main Page</title>
    <meta description='Main Page for LoginReg App'>
    <meta charset='utf-8'/>
</head>
<body>
    <div id='wrapper'>
        <h2> Trip Details. </h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if trips %}
            <h3>{{trips.name}}</h3>
            <h4>Planned By:</h4><p>{{trips.planned_by.name}}</p>
            <h4>The plan:</h4><p>{{trips.description}}</p>
            <h4>Departure date:</h4><p>{{trips.traveldatefrom}}</p>
            <h4>Return date:</h4><p>{{trips.traveldateto}}</p><br>
        {% endif %}

        <h3>Other users' joining the trip:</h3>
        {% for participant in participants %}
            <p>{{participant.name}}</p>
        {% endfor %}

        <form action="{% url 'travels:index' %}" method="GET">
            <button><<< Back </button>
        </form>        
        <form action="{% url 'auth:logout' %}" method="GET">
            <button>Logout</button>
        </form>
    </div>
</body>
</html>